config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :meetings
  resources :sponsers
  resources :events

end

app/models/sponser.rb
class Sponser < ActiveRecord::Base


validates :name, presence: true


end

app/controllers/sponsers_controller.rb
class SponsersController < ApplicationController
  before_action :set_sponser, only: [:show, :edit, :update, :destroy]

  # GET /sponsers
  # GET /sponsers.json
  def index
    @sponsers = Sponser.all
  end

  # GET /sponsers/1
  # GET /sponsers/1.json
  def show
  end

  # GET /sponsers/new
  def new
    @sponser = Sponser.new
  end

  # GET /sponsers/1/edit
  def edit
  end

  # POST /sponsers
  # POST /sponsers.json
  def create
    @sponser = Sponser.new(sponser_params)

    respond_to do |format|
      if @sponser.save
        format.html { redirect_to @sponser, notice: 'Sponser was successfully created.' }
        format.json { render :show, status: :created, location: @sponser }
      else
        format.html { render :new }
        format.json { render json: @sponser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsers/1
  # PATCH/PUT /sponsers/1.json
  def update
    respond_to do |format|
      if @sponser.update(sponser_params)
        format.html { redirect_to @sponser, notice: 'Sponser was successfully updated.' }
        format.json { render :show, status: :ok, location: @sponser }
      else
        format.html { render :edit }
        format.json { render json: @sponser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsers/1
  # DELETE /sponsers/1.json
  def destroy
    @sponser.destroy
    respond_to do |format|
      format.html { redirect_to sponsers_url, notice: 'Sponser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponser
      @sponser = Sponser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponser_params
      params.require(:sponser).permit(:name, :url, :logo)
    end
end

app/helpers/sponsers_helper.rb
module SponsersHelper
end

app/views/sponsers/_form.html.erb
<%= form_for(@sponser) do |f| %>
  <% if @sponser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponser.errors.count, "error") %> prohibited this sponser from being saved:</h2>

      <ul>
      <% @sponser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsers/edit.html.erb
<h1>Editing Sponser</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponser %> |
<%= link_to 'Back', sponsers_path %>

app/views/sponsers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sponsers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsers.each do |sponser| %>
      <tr>
        <td><%= sponser.name %></td>
        <td><%= sponser.url %></td>
        <td><%= sponser.logo %></td>
        <td><%= link_to 'Show', sponser %></td>
        <td><%= link_to 'Edit', edit_sponser_path(sponser) %></td>
        <td><%= link_to 'Destroy', sponser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponser', new_sponser_path %>

app/views/sponsers/new.html.erb
<h1>New Sponser</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsers_path %>

app/views/sponsers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sponser.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @sponser.url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @sponser.logo %>
</p>

<%= link_to 'Edit', edit_sponser_path(@sponser) %> |
<%= link_to 'Back', sponsers_path %>